### ISSUE TITLE
Build-module issue: Function.prototype.apply was called on undefined

### ISSUE THREAD

**Issue by FHantke** [brave/web-discovery-project#370]
Hi,

while building brave from source on an Ubuntu 22.04 server, the process stopped with an error in the web-discovery-project. I basically followed the steps described in the [Linux Development Environment Guide](https://github.com/brave/brave-browser/wiki/Linux-Development-Environment). You can find below the error that `build-module` command throws.

Do you know what goes wrong here? Is it an issue in my setup or a (dependency) bug?

Thank you! 

```zsh
# in web-discovery-project
 npm run build-module

> web-discovery-project@1.1.70 build-module
> node fern.js build configs/module.js --environment prod

Starting build
(node:3305921) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
/path/brave-browser/src/brave/vendor/web-discovery-project/node_modules/esm/esm.js:1

[...]

TypeError: Function.prototype.apply was called on undefined, which is a undefined and not a function
    at $o (/path/brave-browser/src/brave/vendor/web-discovery-project/node_modules/esm/esm.js:1:224377)
    at wu (/path/brave-browser/src/brave/vendor/web-discovery-project/node_modules/esm/esm.js:1:227324)
    at Eu (/path/brave-browser/src/brave/vendor/web-discovery-project/node_modules/esm/esm.js:1:227999)
    at Module.<anonymous> (/path/brave-browser/src/brave/vendor/web-discovery-project/node_modules/esm/esm.js:1:295976)
    at n (/path/brave-browser/src/brave/vendor/web-discovery-project/node_modules/esm/esm.js:1:279589)
    at requireBrocfile (/path/brave-browser/src/brave/vendor/web-discovery-project/node_modules/broccoli/dist/load_brocfile.js:37:20)
    at Object.loadBrocfile (/path/brave-browser/src/brave/vendor/web-discovery-project/node_modules/broccoli/dist/load_brocfile.js:63:22)
    at getBroccoliBuilder (/path/brave-browser/src/brave/vendor/web-discovery-project/fern/common.js:80:29)
    at Command.<anonymous> (/path/brave-browser/src/brave/vendor/web-discovery-project/fern/commands/build.js:70:23)

Node.js v21.4.0
```

**Comment by FHantke** [comment]
Solution for me: Use the correct node.js version 20 :)
